# Generated by Django 5.1.7 on 2025-05-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Ảnh mô tả sự kiện'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả nhà tổ chức'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizers/', verbose_name='Logo nhà tổ chức'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên nhà tổ chức'),
        ),
    ]
