# Generated by Django 5.1.7 on 2025-05-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_description_image_event_organizer_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description_image',
        ),
    ]
