# Generated by Django 5.1.7 on 2025-04-18 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng vé')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Đang chờ thanh toán'), ('Paid', 'Đã thanh toán'), ('Failed', 'Thanh toán thất bại'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã đơn hàng')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phương thức thanh toán')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thanh toán')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_events', to='app.event')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.eventsession')),
                ('ticket_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_tickets', to='app.tickettype')),
            ],
        ),
    ]
