# Generated by Django 5.1.7 on 2025-04-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_cancel_reason_booking_cancelled_at_and_more'),
    ]

    operations = [
    ]
