# Generated by Django 5.1.7 on 2025-04-19 15:54

from django.db import migrations, models


def fix_ticket_type_foreign_keys(apps, schema_editor):
    """
    Sửa khóa ngoại không hợp lệ trong bảng TicketType
    """
    TicketType = apps.get_model('app', 'TicketType')
    EventSession = apps.get_model('app', 'EventSession')
    
    # Lấy các session ID hợp lệ
    valid_session_ids = list(EventSession.objects.values_list('id', flat=True))
    
    if not valid_session_ids:
        return  # Không có session nào, không thể sửa
    
    # Tìm các TicketType có session_id không hợp lệ
    problematic_tickets = TicketType.objects.exclude(session_id__in=valid_session_ids)
    
    # Gán session_id đầu tiên cho các ticket có session_id không hợp lệ
    for ticket in problematic_tickets:
        print(f"Fixing TicketType ID {ticket.id} with invalid session_id: {ticket.session_id}")
        ticket.session_id = valid_session_ids[0]
        ticket.save()


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20250419_2254'),
        ('app', '0001_initial'),  # Thêm dependency vào app để đảm bảo các model của app đã được tạo
    ]

    operations = [
        # Chạy function để sửa khóa ngoại không hợp lệ
        migrations.RunPython(fix_ticket_type_foreign_keys),
        
        # Tạo model BookingItem nếu chưa tồn tại
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Đơn giá')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Thành tiền')),
            ],
        ),
        # Không cố thêm lại các trường đã tồn tại như cancel_reason, cancelled_at, refund_amount
        # Chỉ thêm các trường cho relationships của model BookingItem
        migrations.AddField(
            model_name='BookingItem',
            name='booking',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='booking_items', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='BookingItem',
            name='ticket_type',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='booking_items', to='app.tickettype'),
        ),
    ]
