# Generated by Django 5.1.7 on 2025-04-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='used_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
