# Generated by Django 5.1.7 on 2025-04-01 02:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên sự kiện')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('category', models.CharField(choices=[('concert', 'Hòa nhạc'), ('theater', 'Kịch'), ('sports', 'Thể thao'), ('conference', 'Hội nghị'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Thể loại')),
                ('location', models.CharField(max_length=200, verbose_name='Địa điểm')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Ảnh sự kiện')),
            ],
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.event', verbose_name='Sự kiện')),
            ],
            options={
                'verbose_name': 'Mốc thời gian',
                'verbose_name_plural': 'Mốc thời gian',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại vé')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá vé')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('quantity', models.PositiveIntegerField(default=100, verbose_name='Số lượng vé')),
                ('min_quantity_per_order', models.PositiveIntegerField(default=1, verbose_name='Số lượng vé tối thiểu mỗi đơn')),
                ('max_quantity_per_order', models.PositiveIntegerField(default=10, verbose_name='Số lượng vé tối đa mỗi đơn')),
                ('sale_start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian bắt đầu bán vé')),
                ('sale_end_time', models.DateTimeField(verbose_name='Thời gian kết thúc bán vé')),
                ('ticket_info', models.TextField(blank=True, null=True, verbose_name='Thông tin vé bổ sung')),
                ('ticket_image', models.ImageField(blank=True, null=True, upload_to='tickets/images/', verbose_name='Hình ảnh vé')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='app.eventsession', verbose_name='Mốc thời gian')),
            ],
            options={
                'verbose_name': 'Loại vé',
                'verbose_name_plural': 'Loại vé',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=1, null=True, verbose_name='Giới tính')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
