# Generated by Django 5.1.7 on 2025-04-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_gender_field'),
    ]

    operations = [
    ]
