# Generated by Django 5.1.7 on 2025-04-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_move_session_data_to_event'),
    ]

    operations = [
    ]
