# Generated by Django 5.1.7 on 2025-04-15 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_update_tickettype_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsession',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='app.event', verbose_name='Sự kiện'),
        ),
    ]
