# Generated by Django 5.1.7 on 2025-04-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_convert_to_onetoone_relation'),
    ]

    operations = [
    ]
