# Generated by Django 5.1.7 on 2025-04-15 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_convert_to_onetoone_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsession',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.event', verbose_name='Sự kiện'),
        ),
    ]
