# Generated by Django 5.1.7 on 2025-04-17 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_eventsession_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('concert', 'Âm nhạc'), ('theater', 'Sân khấu & Nghệ Thuật'), ('sports', 'Thể thao'), ('conference', ''), ('other', 'Khác')], default='other', max_length=20, verbose_name='Thể loại'),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.event', verbose_name='Sự kiện'),
        ),
    ]
