# Generated by Django 5.1.7 on 2025-04-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vnpay_bank_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ngân hàng thanh toán'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vnpay_order_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nội dung giao dịch'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vnpay_response_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mã phản hồi'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vnpay_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã giao dịch VNPAY'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vnpay_transaction_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Trạng thái giao dịch'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vnpay_transaction_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian giao dịch'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Đang chờ thanh toán'), ('Paid', 'Đã thanh toán'), ('Failed', 'Thanh toán thất bại'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20),
        ),
    ]
