# Generated by Django 5.1.7 on 2025-04-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_vnpay_bank_code_booking_vnpay_order_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='vnpay_bank_code',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vnpay_order_info',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vnpay_response_code',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vnpay_transaction_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vnpay_transaction_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vnpay_transaction_time',
        ),
    ]
